apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mygoapp
  name: mygoapp
  namespace: mygoapp-ns
spec:
  minReadySeconds: 5
  replicas: {{ .Values.replicaCount }}

  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mygoapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mygoapp
    spec:
      securityContext:
        runAsUser: 82
        runAsGroup: 82
        fsGroup: 82
          # application environment
          envFrom:
            - configMapRef:
                name: mygoapp-app-config
      containers:
        # container with nginx
        - name: nginx
          image: {{ .Values.ecrEndpoint }}/cubbit-task-nginx:{{ .Values.ecrImageId }}
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 88
          resources:
            limits:
              cpu: "250m"
              memory: "300Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 40; /usr/sbin/nginx", "-s", "quit"]

          # # Probes
          startupProbe:
            httpGet:
              path: /api/status
              port: 88
              httpHeaders:
              - name: Host
                value: localhost
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 3

          readinessProbe:
            httpGet:
              path: /api/status
              port: 88
              httpHeaders:
              - name: Host
                value: localhost
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3

          livenessProbe:
            httpGet:
              path: /nginx-ping
              port: 88
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 3

          volumeMounts:
            # nginx main configuration file
            - mountPath: /etc/nginx/nginx.conf
              readOnly: true
              name: nginx-conf
              subPath: nginx.conf

        # container with GO
        - name: mygoapp
          image: {{ .Values.ecrEndpoint }}/cubbit-task-app:{{ .Values.ecrImageId }}
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mygoapp-app-config
          resources:
            limits:
              cpu: "250m"
              memory: "300Mi"
            requests:
              cpu: "50m"
              memory: "150Mi"

          # # Probes
          startupProbe:
            httpGet:
              path: /api/status
              port: 8080
              httpHeaders:
              - name: Host
                value: localhost
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 3

          readinessProbe:
            httpGet:
              path: /api/status
              port: 8080
              httpHeaders:
              - name: Host
                value: localhost
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3

          livenessProbe:
            httpGet:
              path: /api/status
              port: 8080
              httpHeaders:
              - name: Host
                value: localhost
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 3

      volumes:
        # configMap with nginx configuration
        - name: nginx-conf
          configMap:
            name: mygoapp-nginx-conf